### ISSUE TITLE
Infinite captcha submission loop

### ISSUE THREAD

**Issue by tomballgithub** [drallieiv/KinanCity#62]
[2captcha] Number of responses [19] do not match number of requests [40]

Noticed this occur twice recently in an infinite loop.  Last night was after 3-4 hours of success and then it did this for hours until I woke up.  It seems to be using 2captcha $ when this is occurring and burns through account $.  It repeated this forever until I stopped it.  Program was using 40 threads.  KinanCity really needs to stop if this occurs.

https://pastebin.com/WT1vLY6W

**Comment by drallieiv** [comment]
A last I now have a log of that error.

**Comment by drallieiv** [comment]
The first occurence response when it said 
07-04 04:38:47 [2captcha] Number of responses [15] do not match number of requests [33] : 

Does have only 15 values splitted by a pipe, 14 of them being CAPCHA_NOT_READY and one having a response. But at this time there were already 33 captcha sent

If you were running 40 threads it is normal that there would be max 40 captcha ID sent waiting to be checked.

If the response from 2 captcha does not match the request it is normal that they are not de_queued, because it is then impossible to know which captcha response matches which request.

It should only count as captcha $ if you see the log "Request new Captcha"

With 2 captcha, you upload a captcha once, and it gets taken from your balance.
Then you can call it as many time you want to get the corresponding response.
Having a lot of logs for the response request does not mean it cost you any more captcha.

**Comment by drallieiv** [comment]
I have an idea, maybe the list of ids that is sent to 2captcha is too long and gets cut, so while we think we are sending 40 captcha Ids, we are only sending 13 and a half, and we receive the 13 matching responses.

**Comment by tomballgithub** [comment]
OK, well I believed it was costing $ because although it had been hung up like this for hours, 2captcha statistics said I was still consuming 2captcha during those hours.

**Comment by tomballgithub** [comment]
I wasn't seeing the error with 20 threads and subsequently went back to that FYI.  So I do think thread count matters even if it it might be dependent on the computer used

**Comment by drallieiv** [comment]
The thing is I have currently no idea why 2captcha reponds with only 15 or so status, when we ask for 40 of them

**Comment by tomballgithub** [comment]
if you need me to run a special version with debug let me know.

**Comment by drallieiv** [comment]
Captcha ids seems to be 10 digits long plus a comma to split them up
base request is 87 char long.

so a 40 captcha request would be 1800+ chars long.

That may explain why it gets cut somewhere between kinan and 2captcha.

I'll try adding some kind of limit

**Comment by drallieiv** [comment]
Added 2 fixes at once.

First only 20 captchas will be in queue on 2captcha side at once even if more threads are waiting. Their "new captcha" will only be requested once one of the previous one has responded.

Moreover I added a failsafe mode. if the response does not match, it tries with only the first 10

**Comment by drallieiv** [comment]
I am closing that issue, I'll reopen it if that does not fix it.

**Comment by tomballgithub** [comment]
Seems to be working much better.  No issues yet with 40 threads.

**Comment by tomballgithub** [comment]
FYI I made 9K accounts with this change and 40 threads and it did not reproduce.  Thanks
